# Generated by Django 2.2.7 on 2019-11-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lontra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='historico',
            field=models.ManyToManyField(to='lontra.Categoria'),
        ),
    ]
