# Generated by Django 2.2.7 on 2019-11-08 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lontra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='imagens',
        ),
    ]
