# Generated by Django 2.2.6 on 2019-10-19 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lontra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
