# Generated by Django 2.2.7 on 2019-11-20 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lontra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(default='')),
                ('nota', models.IntegerField(default='5')),
                ('receita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lontra.Receita')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lontra.Usuario')),
            ],
        ),
    ]
