# Generated by Django 2.2.7 on 2019-11-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lontra', '0002_remove_receita_imagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='categoria',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
