# Generated by Django 2.2.6 on 2019-10-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lontra', '0002_auto_20191019_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='ingredientes',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='receita',
            name='preparo',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='receita',
            name='url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
