# Generated by Django 2.2.6 on 2019-10-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lontra', '0003_auto_20191019_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='ingredientes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='receita',
            name='preparo',
            field=models.TextField(default=''),
        ),
    ]
