# Generated by Django 2.2.7 on 2019-11-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lontra', '0003_usuario_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='historico',
        ),
        migrations.AddField(
            model_name='usuario',
            name='historico',
            field=models.ManyToManyField(to='lontra.Categoria'),
        ),
        migrations.DeleteModel(
            name='Historico',
        ),
    ]
