# Generated by Django 2.2.7 on 2019-11-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lontra', '0004_auto_20191109_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='categoria',
        ),
    ]
