# Generated by Django 2.2.6 on 2019-10-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lontra', '0004_auto_20191019_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='nota',
            field=models.IntegerField(default=5),
        ),
    ]
