# Generated by Django 2.2.7 on 2019-11-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lontra', '0005_remove_usuario_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='tempo',
            field=models.IntegerField(max_length=255),
        ),
    ]
