# Generated by Django 2.2.6 on 2019-11-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lontra', '0005_receita_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('usuario', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=160)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
