# Generated by Django 2.2.7 on 2019-11-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lontra', '0006_auto_20191124_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='tempo',
            field=models.IntegerField(),
        ),
    ]
