# Generated by Django 2.2.7 on 2019-11-04 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lontra', '0006_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
