# Generated by Django 2.2.7 on 2019-11-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lontra', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
